- src/cljam/bam/core.clj
- src/cljam/bam/reader.clj
- src/cljam/level.clj
Improve a level calculation module as followings,
- split input bam files by chromosomes in a single thread
- apply `claypoole` for multi-thread execution
It reduces memory usage down to 10% or less.
> Save memory usage in level calculation

- src/cljam/bam/reader.clj
I forgot to replace some accessors to an old BAM index (non-delay bai, e.g. `(.index bam-rdr)`)...:pensive:
This PR fixes them.
> Fix access to an old BAM index

- src/cljam/vcf.clj
- src/cljam/vcf/reader.clj
- test-resources/test.vcf
- test/cljam/t_common.clj
- test/cljam/t_vcf.clj
This PR adds functions to read the Variant Call Format (VCF).
* Add `cljam.vcf`: public APIs of VCF I/O
* Add `cljam.vcf.reader`: internal reader functions of VCF
* Add `cljam.t-vcf`: test cases of `cljam.vcf`
* Add `test-resources/test.vcf`: a small VCF file for tests
> Add VCF reader

- src/cljam/pileup/mpileup.clj
- test/cljam/t_pileup.clj
This PR replaces functions to compute mpileup.
- Add characterization tests for previous mpileup implementation.
- Split mpileup function into `pileup-seq` and `gen-mpileup`.
- `pileup-seq`: Create lazy sequence of reads piled up at each locus.
- `gen-mpileup`: Calculate mpileup information (seq and quals) from reads.
> Replace implementation of mpileup

- src/cljam/fastq.clj
- test/cljam/t_fastq.clj
This PR adds a feature to serialize/deserialize FASTQ IDs of illumina.
Using regex to parse ids described in [Wikipedia](https://en.wikipedia.org/wiki/FASTQ_format#Illumina_sequence_identifiers) and [Illumina site](http://support.illumina.com/help/SequencingAnalysisWorkflow/Content/Vault/Informatics/Sequencing_Analysis/CASAVA/swSEQ_mCA_FASTQFiles.htm).
> Parse FASTQ ID

- project.clj
- src/cljam/bam/encoder.clj
- src/cljam/cli.clj
- src/cljam/convert.clj
- src/cljam/util.clj
- src/cljam/util/sam_util.clj
I have improved a performance of SAM/BAM convert function.
- Add encoder of BAM alignment which support parallel processing (See `cljam.bam.encoder`)
- Add SAM/BAM convert functions (See 'cljam.convert)
- Tweak a performance of some functions in `cljam.util.sam-util`
- compressing/decompressing of base codes
- phred score calculation
- Fix some minor issues
> Improve SAM/BAM convert performance

- src/cljam/fasta/core.clj
- src/cljam/fastq.clj
- src/cljam/util.clj
- src/cljam/vcf.clj
This PR adds common compressor stream functions.
* Add `compressor-input-stream` and `compressor-output-stream` to `cljam.util`
* Use those functions in `cljam.vcf`
* Replace existing implementations in `cljam.fasta.core` and `cljam.fastq` with those functions
> Add common compressor stream functions

- README.md
- project.clj
This PR avoids compiled dependencies are included in cljam jar.
Current project settings will pack classes of dependencies in the jar:
```console
$ jar -tf cljam-0.1.5.jar
META-INF/MANIFEST.MF
META-INF/maven/cljam/cljam/pom.xml
META-INF/leiningen/cljam/cljam/project.clj
project.clj
META-INF/leiningen/cljam/cljam/README.md
META-INF/leiningen/cljam/cljam/LICENSE
clj_sub_command/
clj_sub_command/core$apply_options.class
clj_sub_command/core$banner_for.class
clj_sub_command/core$banner_for_commands$fn__100.class
clj_sub_command/core$banner_for_commands$fn__98.class
...
```
This will inclease jar size and cause bugs of multiple dependency versions. `main` and `aot` settings are only required in development and binary generation environments.
> Move main and aot settings to dev and uberjar profiles

- src/cljam/util.clj
Current compressor reader cannot read some compressed files until the end.
```clojure
(with-open [rdr (vcf/reader "/tmp/ALL.chrY.phase3_integrated_v2a.20130502.genotypes.vcf.gz")]
(count (vcf/read-variants rdr)))
;; => 19
```
This PR fixes this problem by setting `decompressUntilEOF` option of `CompressorStreamFactory` to `true`.
```clojure
(with-open [rdr (vcf/reader "/tmp/ALL.chrY.phase3_integrated_v2a.20130502.genotypes.vcf.gz")]
(count (vcf/read-variants rdr)))
;; => 62042
```
The above `ALL.chrY.phase3_integrated_v2a.20130502.genotypes.vcf.gz` is available on ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/
> Enable decompressUntilEOF of CompressorStreamFactory

- src/cljam/bam/decoder.clj
- src/cljam/bam/reader.clj
- src/cljam/bam_index/core.clj
- src/cljam/lsb.clj
- src/cljam/util.clj
- test/cljam/t_bam_indexer.clj
This PR extends `cljam.io/read-alignments` for BAM to support random reading of unplaced reads in BAM file.
Currently, we can't directly access to unplaced reads.
But sequential read is slow because unplaced reads are stored in the last part of BAM file.
I modified the function to read from the end of the last chunk in the last bin if "*" is specified for chr.
This enables a use case like following.
```clojure
(with-open [r (cljam.bam/reader "path/to/bam")]
(cljam.io/read-alignments r {:chr "*" :depth :deep}))
=> ({:rname "*" :pos 0 ...} , ...)
```
> Read unplaced reads in BAM

- src/cljam/vcf/reader.clj
This PR improves performance of reading VCF file.
`cljam.vcf.reader` is slow when reading VCF files like [1000genome](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/) which contains enormous number of genotype fields (> 2500).
This PR fixed 3 problems to make it more than **2x faster**.
- Cache vector of keywords. `keyword` calls `intern` for symbol and keyword which causes locking for static state of runtime.
- Use `apply hash-map` instead of `merge zipmap`. I don't know why but `zipmap` uses persistent map. `hash-map` will use transient hash map and this would be faster.
- Replace `clojure.string/split` with `java.lang.String/split`. [Some implementations](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/lang/String.java#2317) optimize …
> Improve performance of reading vcf file.

- src/cljam/fasta_index/core.clj
- src/cljam/fasta_index/writer.clj
- src/cljam/fasta_indexer.clj
Current FASTA indexer is critically slow because it uses `java.io.RandomAccessFile` to read a source FASTA. This commit improves the performance by using `java.io.BufferedReader`.
The following showd results of indexing 101MB FASTA.
```clojure
;; before:
(time (fai/create-index "/tmp/refMrna.fa" "/tmp/refMrna.fa.fai"))
"Elapsed time: 73621.207302 msecs"
;; after:
(time (fai/create-index "/tmp/refMrna.fa" "/tmp/refMrna.fa.fai"))
"Elapsed time: 2986.332916 msecs"
```
> Improve performance of FASTA indexing

- project.clj
`cider-refresh` fails because of AOT compilation. It's a limitation of tools.namespace (cf. [tools.namespace#warnings-and-potential-problems](https://github.com/clojure/tools.namespace#warnings-and-potential-problems)).
Disabling AOT compilation in dev profile fixes `cider-refresh` error.
This change resolves the error, but refresh takes too long time. `cider-refresh` reloads not only source but also test. midje automatically checks facts just after a namespace is loaded. `:slow :heavy` facts are also checked at this time unexpectedly. This seems to be a bug of midje. I've opened a issue https://github.com/marick/Midje/issues/380. Please ignore it in this PR.
> Fix cider-refresh error

- src/cljam/dedupe.clj
- test/cljam/t_dedupe.clj
This PR adds a function `cljam.dedup/dedup` and a transducer `cljam.dedup/dedup-xform` for removing PCR duplications in paired-end BAM files.
```clojure
(sequence
(dedup/dedup-xform)
[{:qname "r1" :flag 99 :rname "ref" :pos 1 :mapq 60 :rnext "=" :pnext 10 :tlen 5 :qual "IIIII"}
{:qname "r2" :flag 99 :rname "ref" :pos 1 :mapq 60 :rnext "=" :pnext 10 :tlen 5 :qual "IIIIH"}
{:qname "r1" :flag 147 :rname "ref" :pos 10 :mapq 60 :rnext "=" :pnext 1 :tlen -5 :qual "IIIII"}])
=> [{:qname "r1" :flag 99 :rname "ref" :pos 1 :mapq 60 :rnext "=" :pnext 10 :tlen 5 :qual "IIIII"}
{:qname "r1" :flag 147 :rname "ref" :pos 10 :mapq 60 :rnext "=" :pnext 1 :tlen -5 :qual "IIIII"}]
```
Its algorithm is similar to `rmdup` command of samtools.
As mentioned in #2, `MarkDuplicates` command of Picard implements …
> Add functions for deduplicating paired-end BAM.

- src/cljam/dict.clj
- src/cljam/fasta.clj
- src/cljam/fasta/core.clj
- src/cljam/fasta/reader.clj
`cljam.fasta/reader` comes to receive `:ignore-index` option by this commit. (default: `false`)
Current `cljam.fasta/reader` sets `.index` `nil` when an index file is not found. Some functions using index, such as `cljam.fasta/read-sequence`, always returns `nil` if the index is `nil`. This behavior may cause bugs. New `cljam.fasta/reader` disallows nil index unless `:ignore-index true` is passed.
> Add :ignore-index option to cljam.fasta/reader

- src/cljam/sam/reader.clj
- src/cljam/util/sam_util.clj
- test/cljam/util/t_sam_util.clj
This PR fixes a bug in `parse-header` of SAM/BAM files.
Reading SAM/BAM files with too many reference sequences caused StackOverflowError.
This patch replaces explicit recursions with transducers.
> Fix StackOverflowError in parse-header of SAM/BAM files.

- src/cljam/bam.clj
- src/cljam/bam/core.clj
- src/cljam/bam/reader.clj
Reading BAM header and BAI will be time-consuming when BAM has a lot of refs.
Usually we create one reader per ref when process alignments in parallel and reading same BAM header and BAI repeatedly caused degradation of performance.
This PR adds `clone-reader` function to clone BAMReader reconstructing stateful reader objects of Java.
> Add a function to clone bam reader.

- src/cljam/pileup.clj
- src/cljam/pileup/mpileup.clj
- src/cljam/pileup/pileup.clj
- test/cljam/t_pileup.clj
This PR improves performance of pileup. (revised version of #40, this uses feature of #39)
There're two main points.
- use primitive arrays
- make step configurable
Average time of ten profiles piling-up BAM file containing about 65000 alignments in chr1:1-4000000.
[serial]
- before `20918 msecs`
- after `801 msecs`
about 26x faster
[parallel]
- before `8631 msecs`
- after `617 msecs`
about 14x faster
> Improves performance of pileup

- .travis.yml
- README.md
[Codecov](https://codecov.io/) configuration was added.
https://codecov.io/gh/chrovis/cljam
Additionally, caching on Travis CI was set up.
> Integration with Codecov

- project.clj
- src/cljam/cli.clj
[lein-bin](https://github.com/Raynes/lein-bin) plugin is not been maintained anymore. [lein-binplus](https://github.com/BrunoBonacci/lein-binplus) is active fork of lein-bin.
Additionally,
* `:bin {:bootclasspath true}` for launch performance
* `version` sub-command for printing version
were added.
> Use lein-binplus instead of lein-bin

- src/cljam/pileup.clj
- test/cljam/t_pileup.clj
Fix mismatched arity, and add related tests.
> Fix for create-mpileup

- src/cljam/cli.clj
`cljam level` command needs index from internal bam reader, but bam reader without option args means `:ignore-index true`.
Need exipit `:ignore-index false` option.
> Fix for `cljam level` command

- src/cljam/fasta/reader.clj
`newline-character`, `return-character`, `newline*?` and `newline?` were not used, refine it.
> Refine unused code for newline

- test/cljam/t_bam.clj
- test/cljam/t_bam_indexer.clj
- test/cljam/t_pileup.clj
- Reduce too many number of span in pileup test
- Mark `bamreader-medium-file` test as `deftest-slow` (It may causes decreasing of coverage a bit)
- Refine `about-bam-indexer-small-file test`
> For reduce worktime of `lein cloverage`

- test/cljam/t_cli.clj
- test/cljam/t_common.clj
Related items:
- https://github.com/chrovis/cljam/issues/61#issuecomment-297613349
- https://github.com/chrovis/cljam/issues/61#issuecomment-297999405
> Issue #61 (3) Examine result file of `cljam level` test

- README.md
- project.clj
- test/cljam/t_bam.clj
- test/cljam/t_bam_index.clj
- test/cljam/t_bam_indexer.clj
- test/cljam/t_common.clj
- test/cljam/t_sorter.clj
- test/cljam/t_tabix.clj
`:slow` and `:heavy` tests are substantially same on current test-selectors because all `:heavy` tests also have `:slow` tag. It is difficult to run only slow tests with local resources.
`:slow` and `:heavy` tests are clearly separated by this PR.
* `lein test :slow` to run slow tests with local resources.
* `lein test :heavy` to run tests with remote resources.
* `lein test :slow :heavy` to run slow tests with local and remote resources.
> Separate :slow and :heavy test-selectors

- src/cljam/bam/reader.clj
- test/cljam/t_bam.clj
Related to #62
Currently, we get no alignments when giving only chromosome name like `{:chr "chr1"}`.
This is because the default value of start/end is -1/-1.
This PR replaces them with 1 and Long/MAX_VALUE so that `{:chr "chr1"}` will represent whole region of chromosome 1.
> Change default start/end of bam reader.

- src/cljam/core.clj
- test/cljam/t_core.clj
Current `cljam.core` supports only SAM, BAM and FASTA files.
This PR adds other readers/writers to `cljam.core`.
> Extend cljam.core reader/writer functions.

- .travis.yml
- deploy-snapshot.sh
- project.clj
Snapshot on master branch will be automatically deployed to Clojars after all successes of jobs on Travis CI. This function uses a beta feature of Travis CI, [Build Stages](https://blog.travis-ci.com/2017-05-11-introducing-build-stages).
> Setup automatic snapshots deployment

- src/cljam/core.clj
- src/cljam/fasta.clj
- src/cljam/fasta/core.clj
- src/cljam/fasta/writer.clj
- src/cljam/io.clj
- src/cljam/twobit.clj
- src/cljam/twobit/reader.clj
- src/cljam/twobit/writer.clj
- test/cljam/t_core.clj
- test/cljam/t_fasta.clj
- test/cljam/t_io.clj
- test/cljam/t_twobit.clj
This PR adds (naive implementation of) writers for FASTA and 2bit format.
- Add protocol `ISequenceWriter` to `cljam.io`.
- Add `cljam.fasta.writer.FASTAWriter` and `cljam.twobit.writer.TwoBitWriter`.
- Moved readers in `cljam.twobit` to `cljam.twobit.reader`.
- Add function `read-all-sequences` to `ISequenceReader`.
- Fix docstring of `ISequenceReader`.
- Add tests.
- `cljam.fasta`
- `cljam.twobit`
Performance is not yet optimized.
> Add FASTAWriter and TwoBitWriter.

- src/cljam/bam/reader.clj
- src/cljam/cli.clj
- src/cljam/sam/reader.clj
- src/cljam/sam/writer.clj
- src/cljam/sorter.clj
- test/cljam/t_bam.clj
- test/cljam/t_cli.clj
- test/cljam/t_common.clj
- test/cljam/t_sorter.clj
This PR improves functions and performance of `cljam.sorter`.
Also resolves task 7 in #61.
- Improve performance of `sort-by-pos` (about 2x faster).
- Implemented `sort-by-qname`.
- Configurable chunk size.
- Sort SAM and directly output to BAM and vice versa.
- Add tests.
- `cljam.sorter`
- `cljam.bam`
- `cljam.sam`
- `sort-by-pos` does not check `qname`, the same as samtools.
> Improve sorter.

- src/cljam/bcf/reader.clj
- test/cljam/bcf/t_writer.clj
Fixes test redefinition and order of arg vec and docstring.
> Fix test of BCF writer

- test/cljam/io/t_sam.clj
- test/cljam/io/t_sequence.clj
- test/cljam/io/t_util.clj
- test/cljam/io/t_vcf.clj
I forgot to fix commented tests of predicates and old `reader/writer` in `cljam.io.util`. This PR fixes them.
> Fix commented tests

- src/cljam/algo/level.clj
Refactored `cljam.algo.level`
- Reduced the number of stages, 3 => 2.
- [before] serial splitting -> parallel processing -> serial merging
- [after] parallel processing & splitting -> serial merging
- Use volatile thread-local state to compute levels.
> Refactor cljam.algo.level.

- README.md
Sorry, I didn't update README when I renamed `cljam.algo.pileup` to `cljam.algo.depth`.
> Update an example usage of depth in README.

- project.clj
- src/cljam/algo/bam_indexer.clj
- src/cljam/algo/level.clj
- src/cljam/algo/sorter.clj
- src/cljam/io/bam/core.clj
- src/cljam/io/bam/decoder.clj
- src/cljam/io/bam_index/chunk.clj
- src/cljam/io/bam_index/core.clj
- src/cljam/io/bam_index/reader.clj
- src/cljam/io/bam_index/writer.clj
- src/cljam/io/sam.clj
- src/cljam/tools/cli.clj
- test/cljam/algo/t_bam_indexer.clj
- test/cljam/algo/t_sorter.clj
- test/cljam/io/t_sam.clj
- test/cljam/t_common.clj
- test/cljam/tools/t_cli.clj
Overall refactoring of BAI module, including performance improvements.
- Use the linear index to reduce spans.
- For some reason, the linear index was not used to optimize chunks.
- > Given a region [rbeg,rend), we only need to visit a chunk whose end file offset is larger than the file offset of the 16kbp window containing rbeg.
- Search more BAI files for a BAM file.
- Given `"foo.bam"`, `["foo.bam.bai", "foo.bai", "foo.bam.BAI", "foo.BAI"]` are now looked up.
- Use records for chunks.
- Use ref-index instead of rname in bam index writer.
- Remove unused local vars.
Thanks.
> Refactor BAI I/O

- src/cljam/util/chromosome.clj
- test/cljam/util/t_chromosome.clj
This PR adds following features,
- Parse a suffix which represents contig type and version (e.g. `v2_alt`)
- Keep that suffix in lower case to work with reference files that are available from UCSC
- Add a function to determine whether chromosome name is a primary one
> Tweak the normalization function for chromosome name

- bin-resources/log4j2.xml
- project.clj
- src/cljam/tools/cli.clj
Adds a logging configuration (`bin-resources/log4j2.xml`) for cli executable and fixes cli printing. `INFO` logs are printed to stdout and `WARN/ERROR` logs are printed to stderr.
> Add a logging configuration for cli

- src/cljam/algo/dict.clj
- src/cljam/io/fasta/core.clj
- src/cljam/io/fasta/reader.clj
- src/cljam/io/sequence.clj
- test/cljam/io/fasta/t_core.clj
- test/cljam/io/t_sequence.clj
for consistency with https://github.com/chrovis/cljam/pull/96#discussion_r131858258. `:ignore-index` option is removed.
> Make index reading of FASTA reader delayed

- src/cljam/io/bed.clj
- src/cljam/util/chromosome.clj
- test/cljam/util/t_chromosome.clj
This PR adds a function to sort chromosome names in natural order.
```clojure
(sort ["chrX" "chr11" "chr1" "chr2" "chr3" "chrM" "chr22"])
=> '("chr1" "chr11" "chr2" "chr22" "chr3" "chrM" "chrX")
```
```clojure
(sort-by chr/chromosome-order-key ["chrX" "chr11" "chr1" "chr2" "chr3" "chrM" "chr22"])
=> '("chr1" "chr2" "chr3" "chr11" "chr22" "chrX" "chrM")
```
> Add an ordering function for chromosome name.

- src/cljam/algo/depth.clj
`com.climate.claypoole/pmap` consumes extra elements, so that it is inappropriate for lazy sequence. Instead, `cljam.algo.depth/lazy-depth` uses `com.climate.claypoole.lazy/pmap` by this change.
`lazy/pmap` is inferior in speed to `cp/pmap`, but current cljam provides non-lazy `depth` function for performance. I think `lazy/pmap` is useful to handle returned lazy sequence of `lazy-depth`.
> Use lazy pmap for lazy-depth

- src/cljam/util/whole_genome.clj
- test/cljam/util/t_whole_genome.clj
This PR adds some utilities for conversion between chromosomal positions and positions in whole-genome coordinate like [this one](http://software.broadinstitute.org/software/igv/sites/cancerinformatics.org.igv/files/images/igv_gwas.jpg) and [this one](https://www.researchgate.net/profile/Andrey_Alexeyenko/publication/233536110/figure/fig1/AS:214131362799655@1428064303831/Whole-genome-read-coverage-plots-of-A431-blue-U251MG-green-and-U2OS-red-cell-lines.png).
> Add utilities for whole-genome coordinate.

- test/cljam/algo/bam_indexer_test.clj
- test/cljam/algo/dedupe_test.clj
- test/cljam/algo/depth_test.clj
- test/cljam/algo/dict_test.clj
- test/cljam/algo/fasta_indexer_test.clj
- test/cljam/algo/normal_test.clj
- test/cljam/algo/pileup_test.clj
- test/cljam/algo/sorter_test.clj
- test/cljam/io/bam_index_test.clj
- test/cljam/io/bcf/writer_test.clj
- test/cljam/io/bed_test.clj
- test/cljam/io/fasta/core_test.clj
- test/cljam/io/fastq_test.clj
- test/cljam/io/sam/util_test.clj
- test/cljam/io/sam_test.clj
- test/cljam/io/sequence_test.clj
- test/cljam/io/tabix_test.clj
- test/cljam/io/util/cigar_test.clj
- test/cljam/io/util/lsb_test.clj
- test/cljam/io/util_test.clj
- test/cljam/io/vcf/util_test.clj
- test/cljam/io/vcf/writer_test.clj
- test/cljam/io/vcf_test.clj
- test/cljam/test_common.clj
- test/cljam/tools/cli_test.clj
- test/cljam/util/chromosome_test.clj
- test/cljam/util/whole_genome_test.clj
- test/cljam/util_test.clj
Renames test namespaces to conventional names of clojure.test. e.g. `cljam.util.t-chromosome` -> `cljam.util.chromosome-test`
[cider-test](http://cider.readthedocs.io/en/latest/running_tests/) infers a test namespace by adding a suffix, `-test`, so `t-some` namespace cannot be run by `cider-test-run-test`. The inference can be customized in local config, but I feel `some-test` style is better for clojure.test.
> Rename test namespaces to conventional names

- src/cljam/io/bam/reader.clj
- test/cljam/io/sam_test.clj
- test/cljam/io/sequence_test.clj
This PR fixes StackOverflowError in multiple-arity function `cljam.io.protocols/read-in-region` for `cljam.io.bam.reader/BAMReader`.
- Calling the function with 2 args causes `StackOverflowError`.
- `StackOverflowError` does not occurs with 3 args.
2 args function invokes itself instead of 3 args version.
Append an empty map as 3rd arg.
- Added some tests for `cljam.io.protocols/read-in-region` with `.bam`, `.fa` and `.2bit`.
> Fix StackOverflowError in cljam.io.protocols/read-in-region

- bench/cljam/algo/bam_indexer_bench.clj
- bench/cljam/algo/depth_bench.clj
- project.clj
Sets up a benchmark environment using [Libra](https://github.com/totakke/libra).
cljam is a performance-sensitive project, so that we have to take care with degradation when changing it. Libra provides an easy way to check the performance, which is similar to clojure.test and `lein test`.
As a beginning, I added BAM-indexing and depth benchmarks in this PR. `lein libra` runs all defined benchmarks. If you want to run a specific benchmark, you can use `:only` selector: `lein libra :only cljam.algo.depth-bench`.
Libra is still an in-development framework, but I think it has minimum requirements for benchmarking. I plan to add convenient features to it, such as meta-tag selector, CPU/RAM checking, and individual JVMs.
> Set up benchmarks

- src/cljam/io/fasta/core.clj
- src/cljam/io/protocols.clj
- src/cljam/io/sequence.clj
- src/cljam/io/twobit/reader.clj
- test/cljam/io/sequence_test.clj
Add `read-indices` to ISequenceReader protocol, which was defined only for FASTA but not for 2bit.
Also defined an alias function in `cljam.io.sequence`.
> Add `read-indices` to ISequenceReader protocol.

- src/cljam/util/region.clj
- test/cljam/util/region_test.clj
Adds support of comma-separated number in region.
```clojure
(region/parse-region "chr1:1,000-2,000")
;;=> {:chr "chr1", :start 1000, :end 2000}
```
SAMtools also supports such numbers.
```
5. A region should be presented in one of the following formats:
`chr1', `chr2:1,000' and `chr3:1000-2,000'. When a region is
specified, the input alignment file must be a sorted and indexed
alignment (BAM/CRAM) file.
```
> Fix parsing comma-separated number in region

- src/cljam/io/bam/reader.clj
- src/cljam/io/bcf/reader.clj
- src/cljam/io/bed.clj
- src/cljam/io/fasta/core.clj
- src/cljam/io/fastq.clj
- src/cljam/io/protocols.clj
- src/cljam/io/sam.clj
- src/cljam/io/sam/reader.clj
- src/cljam/io/sequence.clj
- src/cljam/io/twobit/reader.clj
- src/cljam/io/vcf/reader.clj
- src/cljam/tools/cli.clj
- test/cljam/io/fasta/core_test.clj
- test/cljam/io/sam_test.clj
- test/cljam/io/sequence_test.clj
- test/cljam/tools/cli_test.clj
Adds region option (`--region`, `-r`) to `view` command.
```console
$ lein run view -r ref2:1-9 test-resources/bam/test.sorted.bam
x1      0       ref2    1       30      20M     *       0       0       AGGTTTTATAAAACAAATAA    ????????????????????
x2      0       ref2    2       30      21M     *       0       0       GGTTTTATAAAACAAATAATT   ?????????????????????
x3      0       ref2    6       30      9M4I13M *       0       0       TTATAAAACAAATAATTAAGTCTACA      ??????????????????????????
```
This feature is only available for indexed BAM, so this PR adds `indexed?` predicate to check the existence of index.
> Add region option to view command

- .travis.yml
- project.clj
- Use dynapath 0.2.5 to avoid ClassNotFoundException
- cloverage 1.0.9 -> bultitude 0.2.8 -> dynapath 0.2.3
- Upgrade dependencies
> Java 9 compatibility

- src/cljam/io/protocols.clj
- src/cljam/io/sam.clj
- src/cljam/io/sequence.clj
Since [`clojure.core/indexed?` will be added in Clojure 1.9](https://github.com/clojure/clojure/blob/a8f1c6436a8bfe181b0a00cf9e44845dcbbb63ee/src/clj/clojure/core.clj#L6199-L6202), this PR excludes it from `cljam.io` module to suppress warnings.
> Don't refer clojure.core/indexed? in cljam.io.

- .travis.yml
The coverage phase accounts for about 2/3 of each build time on CI, and superfluous coverages are currently measured. By moving coverage phase to build stages, the coverage phase will be executed just once and a total of build time will be shortened.
> Move coverage phase to build stages

- src/cljam/algo/convert.clj
- src/cljam/tools/cli.clj
- test/cljam/algo/convert_test.clj
- test/cljam/test_common.clj
- test/cljam/tools/cli_test.clj
Adds FASTA-TwoBit conversion, and test cases also.
As known issue, it is hard to convert a large reference file such as `hg38.fa` because of memory consumption. The reason is that `cljam.io.fasta.reader/sequential-read-string` is non-lazy and `cljam.io.twobit.reader/read-all-sequences` realizes some sequences by chunking. I plan on fixing them on another branch.
> Add FASTA-TwoBit converter

- src/cljam/io/twobit/reader.clj
Current 2bit reader cannot reads small `n` correctly even if `:mask? true` is specified.
For example, when reading the following 2bit file,
```
>ref
nnNN
```
`n` are replaced with `N`.
```clojure
(with-open [rdr (cseq/reader "path/to/nnNN.2bit")]
(doall (cseq/read-all-sequences rdr {:mask? true})))
;;=> ({:name "ref", :sequence "NNNN"})
```
This patch fixes that issue.
```clojure
(with-open [rdr (cseq/reader "path/to/nnNN.2bit")]
(doall (cseq/read-all-sequences rdr {:mask? true})))
;;=> ({:name "ref", :sequence "nnNN"})
```
> Fix a bug that 2bit reader incorrectly reads small n

- .travis.yml
- project.clj
- src/cljam/io/fasta/reader.clj
- test/cljam/io/fasta/core_test.clj
- test/cljam/io/sequence_test.clj
Improve performance of FASTA random reading by **10x** using MappedByteBuffer and CharBuffer.
Current implementation of `read-sequence` for FASTA is slow because of multiple String generation.
byte array => String => String => String
This PR uses mmap and CharBuffer to generate String once.
MappedByteBuffer => CharBuffer => String
```clojure
(are [reg opts] (c/quick-bench (with-open [rdr (cseq/reader "/path/to/hg38.fa")]
(dorun (cseq/read-sequence rdr reg opts))))
{:chr "chr1" :start 1 :end 248956422} {:mask? true}
{:chr "chr1" :start 1 :end 248956422} {})
```
```
[{:chr "chr1", :start 1, :end 248956422} {:mask? true}]
time: 20.807584 sec, sd: 23.176079 ms
[{:chr "chr1", :start 1, :end 248956422} {}]
time: 22.297717 sec, sd: 30.394828 ms
```
```
[{:chr "chr1", :start 1, :end 248956422} …
```
> Improve performance of FASTA random reading

- src/cljam/io/fasta/core.clj
- src/cljam/io/fasta/reader.clj
- src/cljam/io/twobit/reader.clj
- test/cljam/io/sequence_test.clj
Fix for #120 [comment](https://github.com/chrovis/cljam/pull/120#issuecomment-343369370)
> Remove N padding for out-of-range bases in read-sequence.

- src/cljam/io/bed.clj
- src/cljam/io/fastq.clj
- src/cljam/io/vcf/writer.clj
- test/cljam/io/bed_test.clj
Minor fixes for performance improvement and file compatibility.
- Replace (apply str (interpose ...)) with clojure.stirng/join.
- Use CharBuffer to serialize FASTQ.
- Use \tab for delimiting BED fields.
- Although BED fields [can be whitespace-delimited or tab-delimited](https://genome.ucsc.edu/FAQ/FAQformat.html#format1), some tools don't support whitespace-delimited BED.
> Fix some serialization functions.

- src/cljam/io/sam/util.clj
- test/cljam/io/sam/util_test.clj
Don't discard substring after second `:` when parsing SAM header.
Complex SAM headers can be modified unexpectedly.
```
@SQ	SN:A:B;100-200;++;chr1:100-200	LN:400
```
```
@SQ	SN:A	LN:400
```
```clojure
(clojure.string/split "SN:A:B;100-200;++;chr1:100-200" #":")
; => ["SN" "A" "B;100-200;++;chr1" "100-200"]
```
`clojure.string/split` with 2 args splits given string at all ocurrence of the regex.
Pass `2` as 3rd arg (`limit`) of `clojure.string/split`.
SAM/BAM I/O
> Fix parsing SAM header values containing ':'.

- src/cljam/io/fasta/core.clj
- src/cljam/io/util.clj
- test/cljam/io/util_test.clj
Add some file extensions of FASTA format listed in https://en.wikipedia.org/wiki/FASTA_format#File_extension and http://fileformats.archiveteam.org/wiki/FASTA_and_FASTQ.
> Add some extensions for FASTA format.

- src/cljam/io/twobit/writer.clj
- test/cljam/io/sequence_test.clj
Fix a bug that the last 1~3 bases were wrongly padded in the 2bit writer.
When sequence length is not a multiple of 4, last 1~3 bases are not correctly written.
In 2bit writer, every 4 bases are packed into a single byte.
The last bases will be packed from MSB and padded with 2r00.
But there was a bug in padding calculation.
Fix the padding.
2bit writer.
> Fix wrong padding of last bases in 2bit writer

- src/cljam/io/bed.clj
- src/cljam/util/region.clj
- test/cljam/io/bed_test.clj
This PR adds the following new APIs to `cljam.io.bed`:
- `intersect-fields`
- `subtract-fields`
- `complement-fields`
Each implementation reflects the behavior of `bedtools`' corresponding subcommand. See  the links below for details:
- intersect: http://bedtools.readthedocs.io/en/latest/content/tools/intersect.html
- subtract: http://bedtools.readthedocs.io/en/latest/content/tools/subtract.html
- complement: http://bedtools.readthedocs.io/en/latest/content/tools/complement.html
There is one thing to be confirmed.
`complement-fields` now throws an exception if the map passed as the first argument (`chrom-lengths`) lacks the entry for some chromosome appeared in the sequence of BED fields. However, the exception will be deferred until the resulting sequence is realized because …
> Add some BED manipulation APIs

- .travis.yml
- deploy-snapshot.sh
- project.clj
- Upgrade outdated dependencies
- Use Clojure 1.9 for `:dev` and `:uberjar` profiles (#133)
- Add some more JDK versions for CI
- Some installed certificates in JDKs need to be overwritten to connect to clojars. https://stackoverflow.com/questions/50712164/clojure-build-failed-on-travis-ci-with-openjdk-9-during-lein-deps
> Upgrade dependencies

- src/cljam/io/vcf/reader.clj
- src/cljam/io/vcf/writer.clj
- test/cljam/io/vcf/reader_test.clj
- test/cljam/test_common.clj
This PR provides character escaping support for VCF string fields (that was reported in #135).
With this change, you'll be able to use the characters `\` and `"` in VCF string fields by escaping them with `\`, such like `\\` and `\"`.
```clj
(require '[cljam.io.vcf.reader :as reader])
(#'reader/parse-structured-line "ID=ID,Description=\"\\\"This\\\" is a description\",Note=\"You can use \\\" in string fields by escaping it with \\\\\"")
;=> {:id "ID", :description "\"This\" is a description", :note "You can use \" in string fields by escaping it with \\"}
```
It also improves error checking for string field format:
```clj
(#'reader/parse-structured-line "x=\"unbalanced double quote")
;; RuntimeException Unexpected end of string field
(#'reader/parse-structured-line "x=\"unknown \\x escape …
```
> Character escaping support for string fields in VCF meta info

- src/cljam/algo/pileup.clj
- test/cljam/algo/pileup_test.clj
- Add an `ignore-overlaps?` option to `cljam.algo.pileup/pileup`
- Skip filtering bases when `min-base-quality` is ~zero~ not positive
> Fix options of cljam.algo.pileup/pileup

- src/cljam/io/pileup.clj
- test/cljam/algo/pileup_test.clj
This PR fixes a bug in `cljam.algo.pileup/pileup`.
IllegalArgumentException in `cljam.algo.pileup/pileup`
```
java.lang.IllegalArgumentException: Value out of range for byte: 186
```
The `qual` field in `cljam.io.pileup.PileupBase` is declared as a `byte` because a phred-33 encoded base quality score never exceeds `93`:
https://github.com/chrovis/cljam/blob/02addc40def7515d2f30db8032fe4cf9776c5bd8/src/cljam/io/pileup.clj#L15
The record is also constructed in `cljam.algo.pileup`:
https://github.com/chrovis/cljam/blob/02addc40def7515d2f30db8032fe4cf9776c5bd8/src/cljam/algo/pileup.clj#L85-L94
But quality scores can be `128` ~ `200` while piling alignments up with the option `:ignore-overlaps false`:
https://github.com/chrovis/cljam/blob/02addc40def7515d2f30db8032fe4cf9776c5bd8/src/cljam/algo/ …
> Fix a bug in `cljam.algo.pileup/pileup`

- .travis.yml
- project.clj
- src/cljam/algo/pileup.clj
- src/cljam/io/pileup.clj
For clarification and better performance,
- Remove `count` and `ref` fields from `defrecord` of `cljam.io.pileup.LocusPile`
- optional for `cljam.io.pileup.PileupReader`
- Always fill `mapq` of `cljam.io.pileup.PileupBase` when available
> Fix some fields of cljam.io.pileup LocusPile and PileupBase

- bench/cljam/io/sequence_bench.clj
- src/cljam/io/fasta/core.clj
- src/cljam/io/protocols.clj
- src/cljam/io/sequence.clj
- src/cljam/io/twobit/reader.clj
- test/cljam/io/sequence_test.clj
Quick fix for #150 : Random read of 2bit is quite slower than FASTA
Now it got about **20x ~ 35x** faster than master
https://github.com/chrovis/cljam/blob/7921def33b712c099fd6cac94fe1e98ca2a94c76/bench/cljam/io/sequence_bench.clj#L7-L9
https://github.com/chrovis/cljam/blob/7921def33b712c099fd6cac94fe1e98ca2a94c76/bench/cljam/io/sequence_bench.clj#L15-L22
https://github.com/chrovis/cljam/blob/7921def33b712c099fd6cac94fe1e98ca2a94c76/bench/cljam/io/sequence_bench.clj#L28-L37
```clj
read-all-sequences-test (sequence_bench.clj:7)
["test-resources/fasta/medium.fa" {}]
time: 78.420780 ms, sd: 7.932527 µs
["test-resources/fasta/medium.fa" {:mask? true}]
time: 80.570329 ms, sd: 27.922591 µs
["test-resources/twobit/medium.2bit" {}]
time: 121.734670 ms, sd: 1.247978 µs …
```
> Improve performance of TwoBitReader

- src/cljam/io/bed.clj
- test/cljam/io/bed_test.clj
**BREAKING CHANGE**
Decouple chromosome name normalization from BED i/o.
Chromosome name normalization is an irreversible transformation and should not be complected.
- removed `cljam.util.chromosome/normalize-chromosome-key` used in `cljam.io.bed/read-fields`
- removed `cljam.io.bed/read-raw-fields` and `cljam.io.bed/write-raw-fields`which are no longer necessary
> Remove normalization of chromosome names from BED reader

- src/cljam/io/bam/decoder.clj
- src/cljam/io/bcf/reader.clj
- src/cljam/io/fasta/reader.clj
- src/cljam/io/fastq.clj
- src/cljam/io/sam/util/quality.clj
- src/cljam/io/sam/util/sequence.clj
- src/cljam/io/twobit/reader.clj
- src/cljam/io/util/lsb.clj
- src/cljam/util/sequence.clj
This PR fixes #158.
Basically, it's just type-hinting with `Buffer` the receiver of each call to the following `ByteBuffer`/`CharBuffer` methods (some of the changes might look somewhat tricky, though):
- `clear()`
- `flip()`
- `limit(int)`
- `mark()`
- `position(int)`
- `reset()`
- `rewind()`
All the problematic call sites are listed [here](https://gist.github.com/athos/bc8d6e2ff28318f1ec61a4baf73588dd).
I've tested an uberjar built on Java 11, running `lein check` and `lein test :all` on Java 8 and Java 11.
> Fix ByteBuffer/CharBuffer methods incompatibility

- src/cljam/algo/pileup.clj
- test/cljam/algo/pileup_test.clj
Pileup alignments per chunk to improve the performance
```clojure
(time (with-open [r (sam/reader "/path/to/bam/SRP006438.chr1.bam")]
(dorun (pileup/pileup r {:chr "chr1", :start 152210000, :end 152214999}))))
```
- master: 8523 ms
- PR: 6013 ms (-29.4%)
- master: `time: 56.355322 sec, sd: 4.858070 ms`
- PR: `time: 55.349883 sec, sd: 7.576505 ms` (-1.8%)
- Read and make chunks which have all pairs
- Correct `quals-at-ref` of an overlapping pair by looking up `quals` in the corrected quals map
- Pileup alignments in each chunk
- Add pileup tests
> Improve pileup by chunking alignments

- src/cljam/io/vcf/util.clj
- test/cljam/io/vcf/util_test.clj
This PR fixes VCF INFO parsing errors when empty values pass.
If `nil` comes to the line below,
https://github.com/chrovis/cljam/blob/773eb527a09b2d206ee567c8a93eeee27162f065/src/cljam/io/vcf/util.clj#L27
it transforms to an empty string.
So `NumberFormatException` in `Integer/parseInt` and `Float/parseFloat` occurs, because `dot-or-nil?` doesn't catch empty strings.
- Add empty check into `dot-or-nil?`
- VCF reader
- BCF reader
- `lein check` 🆗 
- `lein test :all` 🆗 
> Skip INFO value parsing if it's empty

- src/cljam/io/vcf/reader.clj
- src/cljam/io/vcf/util.clj
- test/cljam/io/vcf/util_test.clj
This PR adds 4 utility functions related to genotype ordering in VCF.
I've refined the implementation a bit.
Basically, these are useful for working with genotype information values defined as `Number=G` like genotype likelihoods `GL`.
Such values should be provided for all possible genotypes with given ploidy and number of alleles (`REF` + `ALT`).
For more details, please refer to the [spec "VCFv4.3 1.6.2 Genotype fields"](https://github.com/samtools/hts-specs/blob/d962e2fc9e2456c737a91e88cbc40ccf4a732650/VCFv4.3.tex#L442).
- `genotype-seq`: list all genotypes
- `genotype-index`: get an index for a genotype
- `biallelic-genotype`: multiallelic genotype string to biallelic one
- `biallelic-coll`: multiallelic genotype-wise values to biallelic one
- …
> Add utility functions for manipulating genotypes

- src/cljam/io/vcf/util.clj
- test/cljam/io/vcf/util_test.clj
This PR adds basic support for breakends in VCF.
Breakends are variant records which have `SVTYPE=BND` in the `INFO` field.
They have a dedicated format of string representation for `ALT` field.
For more details, please refer to the [spec "5.4 Specifying complex rearrangements with breakends"](https://github.com/samtools/hts-specs/blob/d962e2fc9e2456c737a91e88cbc40ccf4a732650/VCFv4.3.tex#L859)
- `lein cloverage` 🆗
> Add support for breakends in VCF

- src/cljam/io/vcf/util.clj
- test/cljam/io/vcf/util_test.clj
~~**This PR is depending on #163**~~
This PR adds a function to inspect an `ALT` allele of a variant in VCF.
The `ALT` field of VCF is so expressive that it is not so straightforward to know what they mean.
`cljam.io.vcf.util/inspect-allele` provides a way to classify `ALT` alleles into ~~9~~ ~~10~~ 13 types.
With this feature, we can easily transform VCF variants based on their types. (e.g. filtering only SNPs)
- `lein cloverage` 🆗
> Add a function to inspect an ALT allele of VCF

- src/cljam/algo/pileup.clj
- src/cljam/io/pileup.clj
- src/cljam/io/sam/util/flag.clj
- test/cljam/io/pileup_test.clj
Improve the performance of pile up
- Add `alignment` to `PileupBase` to remove `assoc`
- Improve `correct-pair-quals` by using ~~transient vectors~~ a transducer
- ~~Improve `index-cigar` by making `seqs-at-ref` and `quals-at-ref` at once~~
-　(Tips) I've tried to make new `index-cigar` for pileup to make them without index, however, it's not effective. That's because these index made by `(memoize to-index*)` makes this process fast.
- Call `clojure.lang.Numbers#bitTest` for `long` directly to avoid many casts.
- Add some type hints
- `lein cloverage` 🆗  
- sample: WES SRP006438.sorted.bam
- many alignments chr1:152210000-152214999  (improved by 15.7%)
|branch|time|
|----|----|
|master|time: 7.490895 sec, sd: 46.194343 ms|
|feature/improve-pileup …
> Improve pileup more

- src/cljam/io/vcf/util/check.clj
- src/cljam/io/vcf/util/normalize.clj
- test/cljam/io/vcf/util/check_test.clj
- test/cljam/io/vcf/util/normalize_test.clj
~~**This PR is depending on #164**~~
Add `cljam.io.vcf.util.normalize/normalize` which converts variants into canonical forms.
cf. `bcftools norm -m-`
See the test cases for typical conversion examples.
```
ref0: TATTTTTTTTTTTT TC  TTTTT
alt1:                TTCC     <- not right-trimmed
alt2:                TTC      <- not right-trimmed
ref0: TATTTTTTTTTTTT T  CTTTTT
alt1:                TTC
alt2:                TT       <- not left-aligned
ref0: T A TTTTTTTTTTTT T  CTTTTT
alt1:                  TTC
alt2:   AT
```
**input** multiallelic, not left-aligned, not right-trimmed
https://github.com/chrovis/cljam/blob/41881832c20f96c25d91027a73cab09a34378950/test/cljam/io/vcf/util/normalize_test.clj#L328-L330
**output** biallelic, left-aligned, right-trimmed …
> Normalize variants in a VCF file

- project.clj
- src/cljam/io/bcf/reader.clj
- src/cljam/io/vcf/util.clj
- src/cljam/io/vcf/writer.clj
- test/cljam/io/vcf/util_test.clj
- test/cljam/io/vcf/writer_test.clj
- test/cljam/test_common.clj
This PR fixes three minor bugs in VCF/BCF I/O
1. Writing `:info {}` does not emit `.` (VCF)
https://github.com/chrovis/cljam/blob/f91f8164db66ec89ac67cf2b298dfff9a7c42179/test/cljam/io/vcf/writer_test.clj#L50-L51
2. Writing a variant map without samples will cause a NPE (VCF)
https://github.com/chrovis/cljam/blob/f91f8164db66ec89ac67cf2b298dfff9a7c42179/test/cljam/io/vcf/writer_test.clj#L62-L63
3. Omitted genotype fields are totally ignored (VCF/BCF)
e.g. Reading `DP:HQ	4:51,51	2` does not assoc `:HQ nil` to the 2nd sample.
https://github.com/chrovis/cljam/blob/f91f8164db66ec89ac67cf2b298dfff9a7c42179/test/cljam/test_common.clj#L711-L714
- `lein cloverage` 🆗
> Fix I/O of variants with empty info/individual fields

- src/cljam/io/bcf/writer.clj
- test/cljam/io/bcf/writer_test.clj
`cljam.io.bcf.writer/write-variants` fails to encode variants if they contain keys not declared in `meta-info`.
This PR fixes the bug by ignoring such keys.
https://github.com/chrovis/cljam/blob/94ce1f8de25130bc2a28aa5a03e3fec3e34672f9/test/cljam/io/bcf/writer_test.clj#L256-L258
https://travis-ci.org/chrovis/cljam/jobs/552587080#L535-L554
> Ignore undeclared keys in INFO and FORMAT when writing BCF files

- .travis.yml
- src/cljam/io/bcf/writer.clj
- test/cljam/io/bcf/writer_test.clj
~~**This PR depends on #169**
The actual diff is [94ce1f8...581438a](https://github.com/chrovis/cljam/pull/170/files/94ce1f8de25130bc2a28aa5a03e3fec3e34672f9..581438a1502bf4ab1af0d4b1ea74970b3d876320)~~
Like VCFWriter, this PR provides a default file format version `"VCFv4.3"` for meta-info of BCF.
Though BCF has its version in the magic number `BCF\2\2`, the header string should start with `##fileformat=`.
> Provide a default file format version for BCF

- test/cljam/io/fastq_test.clj
- test/cljam/io/sequence_test.clj
- test/cljam/io/util/lsb_test.clj
`temp-dir` has a type of `java.lang.String` and the end is not `"/"`, so `"/"` is needed when concatenating `temp-dir` with files.
This PR fixes nonintentional paths that do not contain `"/"`, does not change the test results.
> Fix nonintentional paths

- src/cljam/io/sam/util/cigar.clj
- test/cljam/io/sam/util/cigar_test.clj
`cljam.io.bam` fails to decode alignments with CIGAR operations longer than 134217728
A CIGAR is stored as an array of `op_len<<4|op` in `uint32_t[n_cigar_op]`.
Thus `op_len` can be as long as 28bit `0x0FFFFFFF` but it is not handled properly due to type promotion from int to long.
Use `Integer/toUnsignedLong` to get a positive long value.
- `lein cloverage` 🆗
> Fix decoding of long CIGAR ops in BAM

- test/cljam/io/bigwig_test.clj
This PR avoids all reflections except those of external libraries when running `lein with-profile +dev test`.
> Fix reflection warnings

- src/cljam/algo/depth.clj
- src/cljam/io/bam_index/writer.clj
- src/cljam/io/bigwig.clj
- src/cljam/io/sam/util/header.clj
- src/cljam/io/vcf/util.clj
This PR fixes minor typos. It's mainly misspelling, so maybe there are still some grammatical errors that involve misunderstanding.
> Fix minor typos

- src/cljam/algo/sorter.clj
- src/cljam/io/bcf/reader.clj
- src/cljam/io/bed.clj
- src/cljam/io/sam/util/flag.clj
- src/cljam/io/util/lsb.clj
- src/cljam/io/vcf.clj
- src/cljam/util.clj
This PR fixes minor grammar mistakes:
- `an` follows the word starts with a vowel sound.
- `a` follows the word doesn't start with a vowel sound.
- Superlative takes `the`.
- It needs a comma after a conjunctive adverb.
> Fix grammar

- src/cljam/algo/level.clj
- src/cljam/algo/sorter.clj
- src/cljam/util.clj
- test/cljam/io/bcf/writer_test.clj
- test/cljam/io/pileup_test.clj
- test/cljam/io/sam_test.clj
- test/cljam/io/sequence_test.clj
- test/cljam/io/util_test.clj
- test/cljam/io/vcf_test.clj
- test/cljam/io/wig_test.clj
- test/cljam/util_test.clj
In the current implementation of creating temporary user's directory, there are two problems: always creates the directory of the same name `cljam`, and doesn't delete it after all is done. That might cause `Permission denied` if multiple users run cljam on the same machine.
This PR fixes the behavior; `with-temp-dir` macro creates an unique directory, and finally deletes it. Also, fixes a path to temporary directory such that the test code creates user's directory instead of test's directory.
> Fix creating temp directory to support multiple users

- src/cljam/io/bam_index/writer.clj
- test/cljam/algo/bam_indexer_test.clj
`cljam.algo.bam-indexer/create-index` throws an `clojure.lang.ArityException` when the target BAM contains no alignments
An initial value is not provided for `(reduce merge-index [])` in `cljam.io.bam-index.writer/make-index-from-blocks`
https://github.com/chrovis/cljam/blob/2db7fe739047e2284e93e9d211be74cfdd6cc09b/src/cljam/io/bam_index/writer.clj#L310
Add a default value for `make-index-from-blocks`
- `cljam.algo.bam-indexer`
- `cljam.io.bam-index.writer`
- `lein check` ✅
- `lein test :all` ✅
> Avoid an ArityException on creating an index for BAM files without alignments

- .github/workflows/main.yml
The build 14 of OpenJDK EA has been deleted after build 25 is published.
We need to get the latest build number automatically to adapt to future releases.
This PR picks up a tarball URL from the HTML of jdk.java.net then [`set-env`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env) it to use it from `actions/setup-java`.
> Detect the latest build number of OpenJDK EA

- src/cljam/io/vcf.clj
- src/cljam/io/vcf/reader.clj
- test/cljam/io/vcf_test.clj
`cljam.io.vcf/read-variants` throws `java.lang.ClassCastException` for bgzipped VCF files.
#180 introduced switching of reader type between `java.io.BufferedReader` and `bgzf4j.BGZFInputStream` but did not modify the existing code.
Switch methods based on the type of reader instance.
- `lein check` ✅
- `lein test :all` ✅
- `lein cloverage` ✅
> Fix a bug in reading bgzipped VCF files

- src/cljam/io/bcf/reader.clj
In some environments such as "IcedTea",Float reader in Bcf reader doesn't  work as expected.
Specifically, the result of reading NaN is expected to be 0x800001, but the result will be different.
The fix is ​​to read as int and convert to float if not NaN.
> Fix float reader for specific environments such as IcedTea.

- src/cljam/algo/pileup.clj
`cljam.algo.pileup` tends to consume a very large amount of memory and in the worst case it ends up with OOME.
This PR mitigates the situation by improving memory efficiency for the pileup data structure. The primary changes are as follows:
- Use more space-efficient data structures (eg. primitive arrays, dedicated deftypes) to represent a pileup result
- Drop unnecessary intermediate data (`:seqs-at-ref` / `:quals-at-ref` ) from the pileup result
- Unchunk a pileup result (which was a chunked sequence) and return a lazy sequence instead to make each element easier to consume and deallocate one by one
In my small examination, the changes reduced the memory usage by ~45% at peak time with almost no impact on time efficiency:
See [here](https://docs.google.com/spreadsheets/d/1HiCzozDYk5iFR_n …
> Improvement for pileup memory usage

- project.clj
- src/cljam/io/sam/util/cigar.clj
cljam has [a memoizing cache for parsed CIGAR strings](https://github.com/chrovis/cljam/blob/c320af1a4a17ac0af06a7da438fac1d6ec909825/src/cljam/io/sam/util/cigar.clj#L48), and it tends to limitlessly increase in size after a long-term process such as pileup. The following chart shows how large the whole memory usage got during a certain run of variant call using cljam's pileup. Note that the bottom line of the used heap size is steadily getting higher as time goes along:
This PR replaces the memoizing cache with [core.memoize](https://github.com/clojure/core.memoize)'s LU cache, limiting the cache size to an appropriate upper bound. Also, it defines a new system property named `cljam.sam.cigar.cache-size` to specify the upper bound of cache size when launching the JVM.
After applying the …
> Replace memoizing cache for parsed CIGARs with core.memoize's LU cache

- .github/workflows/lint.yml
I added lint action.
The "clj-lint action" is added to the first of some actions (coverage, format, int, main).
> Add lint actions.

- .github/workflows/lint.yml
This PR adds the option of clj-lint-action.
Without this option, the second commit on the branch would not be able to take the diff.
> Add base_sha option to clj-lint-action.

- .github/workflows/main.yml
Added a step to run `lein check` on CI (for only Java 11).
It will report reflection warnings using [workflow commands](https://help.github.com/ja/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message).
> Run lein check on CI

- src/cljam/io/vcf.clj
- test/cljam/io/vcf_test.clj
This PR adds a function to create a new object by copying except stream when VCF/BCF object is put in the reader.
This function is almost the same as "cljam.io.bam.core/clone-reader".
> Add support cloning VCF/BCF.

- src/cljam/io/util/bin.clj
- test/cljam/io/util/bin_test.clj
Refactored `cljam.io.util.bin`
- Rearrange functions
- Add docstrings
- Add tests
- `lein check` ✅ 
- `lein test :all` ✅ 
- `lein cloverage` ✅
- `lein eastwood` ✅
- `lein cljfmt check` ✅
> Refactor cljam.io.util.bin

- src/cljam/algo/convert.clj
- src/cljam/io/bam/core.clj
- src/cljam/io/bam/writer.clj
- src/cljam/io/bam_index/writer.clj
- src/cljam/io/sam.clj
- src/cljam/tools/cli.clj
- test/cljam/io/bam_index/writer_test.clj
- test/cljam/io/sam_test.clj
This PR is to add a function to create an index file if it is already sorted when creating a BAM file.
PR for issue #141 .
> Create an index file while writing a sorted BAM file

- .github/workflows/lint.yml
I updated the version of clj-lint-action so that the config of clj-kondo can be read.
In this version upgrade of clj-lint-action, the command to move the working directory to the repository and the line break of the source code have been added.
> Update the version of lint-action to read the clj-kondo config file.

- .github/dependabot.yml
This PR adds settings for GitHub Dependabot to keep GitHub Actions dependencies up to date.
Currently, GitHub Dependabot checks only GitHub Actions dependencies, not others in `project.clj`.
> Introduce GitHub Dependabot to keep dependencies up to date

- src/cljam/util/intervals.clj
- test/cljam/util/intervals_test.clj
This pr adds support for Nested Containment List (NCList).
- Add a second argument to "make-sorted-map-intervals" to select the data structure.
- In the original, it is represented by two lists, but in order to represent it in Clojure, it is represented by one nested list.
> Add support for nclist.

- src/cljam/io/bcf/reader.clj
- src/cljam/io/vcf.clj
- src/cljam/io/vcf/reader.clj
- test/cljam/io/vcf_test.clj
Since `indexed?` of vcf / bcf was not implemented, I added it.
The implementation is almost the same as the `indexed?` of fasta.
> Add support for indexed? for vcf/bcf.

- .github/workflows/main.yml
As Java [14](https://jdk.java.net/14/) has been moved to [the archive](https://jdk.java.net/archive/), CI is [failing](https://github.com/chrovis/cljam/pull/214/checks?check_run_id=1410471239).
This PR fixes CI by updating Java versions to the LTS (`1.8`, `11`), the latest (`15`), and the EA (`16-ea`) using [actions/setup-java](https://github.com/actions/setup-java).
> Update java versions for testing

- .github/workflows/format.yml
- .github/workflows/main.yml
Related to: #224 
The differences between v1 and v2 are listed in https://github.com/actions/setup-java#v2-vs-v1
- v2 requires `distribution:` value, which is set to `adopt` here
- v2 requires `java-version:` to be a SemVer
> Update actions/setup-java to v2

- src/cljam/io/vcf/util.clj
I added exception information about which INFO key is the problem to make it easier to understand the exception when reading the VCF, such as missing a reserved INFO key.
I've seen type errors during INFO parsing in the past, but I lost the VCF file that caused it, so I didn't add any other checking features this time.Then I had Cljam read some VCF files (known databases and others) and found no other problems, so I'll do the rest when I find them.
> Add explanation to info exception.

- src/cljam/util/intervals.clj
- test/cljam/util/intervals_test.clj
When issuing an interval query (using `c.u.i/find-overlap-intervals`) for a missing chr in the index, an error will be thrown:
```clojure
(require '[cljam.util.intervals :as intervals])
(def index
(intervals/index-intervals
[{:chr "chr1", :start 10000, :end 15000}
{:chr "chr1", :start 20000, :end 25000}]))
(intervals/find-overlap-intervals index "chr1" 13000 17000)
;=> ({:chr "chr1", :start 10000, :end 15000})
(intervals/find-overlap-intervals index "chr1" 17000 19000)
;=> ()
(intervals/find-overlap-intervals index "chr2" 13000 17000)
;; Execution error (IllegalArgumentException) at cljam.util.intervals/eval5662$fn$G (intervals.clj:4).
;; No implementation of method: :find-overlap-intervals* of protocol: #'cljam.util.intervals/IIntervals found for class: nil
```
This PR fixes the error by …
> Fix error that occurs when querying intervals for missing chr

- src/cljam/io/vcf/reader.clj
With current implementation, many lines of meta (say 4k lines of contig definition) causes StackOverflowError like below.
```
:cause nil
:via
[{:type java.lang.StackOverflowError
:message nil
:at [clojure.lang.PersistentHashMap$BitmapIndexedNode ensureEditable "PersistentHashMap.java" 812]}]
:trace
[[clojure.lang.PersistentHashMap$BitmapIndexedNode ensureEditable "PersistentHashMap.java" 812]
[clojure.lang.PersistentHashMap$BitmapIndexedNode assoc "PersistentHashMap.java" 894]
[clojure.lang.PersistentHashMap$TransientHashMap doAssoc "PersistentHashMap.java" 327]
[clojure.lang.ATransientMap assoc "ATransientMap.java" 64]
[clojure.lang.PersistentHashMap create "PersistentHashMap.java" 78]
[clojure.core$hash_map invokeStatic "core.clj" 389]
[clojure.core$hash_map doInvoke "core.clj" 381] …
```
> Avoid StackOverflowError while reading a VCF with many lines of meta

- project.clj
- src/cljam/util.clj
- test/cljam/util_test.clj
Fixes #251 
This PR changes the behavior of `cljam.util/compressor-output-stream`.
It now returns `BGZFOutputStream` instead of `GzipCompressorOutputStream` for files with `.gz` extension.
Since BGZIP is just a special case of GZIP, existing codes using `cljam.util/compressor-output-stream` with `.gz` should still work.
To get `GzipCompressorOutputStream`, we can use the 2nd argument or `.gzip` extension.
This PR also includes
- Update log4j to 2.17.0
- Some minor fixes suggested by linters
> Use bgzip as default for writing `.gz` files

- src/cljam/io/vcf/util.clj
- test/cljam/io/vcf/util_test.clj
The current latest VCF spec ([v4.4](https://github.com/samtools/hts-specs/blob/master/VCFv4.4.pdf)) allows explicitly specifying the first phasing indicator of a genotype (like `/0/1` or `|0/1/2`), and defines the semantics for when it's omitted as below:
> The first phasing indicator may be omitted and is implicitly defined as `/` if any phasing indicators are `/` and `|` otherwise.
https://github.com/samtools/hts-specs/blob/0dd3e0d7c6f02b0627a29d6cbab777df07b4daad/VCFv4.4.tex#LL509C5-L509C136
This PR supports explicitly specifying the first phasing indicator to genotypes, and changes the genotype stringifier to emit it if necessary.
> Support explicit first phasing indicator for VCF genotypes

- src/cljam/io/vcf/util/validator.clj
- test/cljam/io/vcf/util/validator_test.clj
I add VCF4.4 validator for writing.
see also #271
> Add validator for writing vcf.

- .github/workflows/coverage.yml
Reverts chrovis/cljam#284
Codecov v4 is a beta version, there is no release itself , so I think it is better to revert it.
> Revert "Bump codecov/codecov-action from 3 to 4"

- src/cljam/algo/depth.clj
- src/cljam/io/bam/reader.clj
This PR includes the following two small changes to improve the performance of `cljam.algo.depth`:
- 736a9bc: Uses `run!` to avoid unnecessary sequence allocation
- 3b15a95: Reads BAM raw blocks into chunked seq, instead of cons, to improve the performance of later processing
The timing results are as follows:
```clojure
(time
(with-open [r (sam/reader "DRR002191.chr1.bam")]
(run! (constantly nil)
(depth/depth r {:chr "chr1"} {:unchecked? true :n-threads 8}))))
;; before the changes
"Elapsed time: 4760.83475 msecs"
;; with 736a9bc
"Elapsed time: 4247.021042 msecs"
;; with 736a9bc + 3b15a95
"Elapsed time: 3983.6545 msecs"
```
The second change only shows a relatively small performance gain and might not need to be included in this PR.
For reference, here are the flamegraphs resulting from …
> Misc performance tuning for cljam.algo.depth

- bench/cljam/io/vcf_bench.clj
- src/cljam/io/bam/decoder.clj
- src/cljam/io/bcf/reader.clj
- src/cljam/io/util/byte_buffer.clj
- test/cljam/io/util/byte_buffer_test.clj
This PR is the first step of #289.
It replaces the use of `ByteBuffer` as an LSB protocol implementation with a new thin wrapper utility for `ByteBuffer`.
The modification policy here is to use the bare `ByteBuffer` methods whenever possible. The new wrapper namespace only collects functions that do what a single method of `ByteBuffer` cannot do. Most of the implementation code comes from [the implementation of the LSB protocol](https://github.com/chrovis/cljam/blob/14e0deb16f4423686d5d68907e040fe9729d262d/src/cljam/io/util/lsb.clj#L36-L82).
> Use ByteBuffer wrapper instead of LSB protocol

- src/cljam/io/bcf/reader.clj
When I was profiling the BCF reader before, I found that the invocation to [`nth`](https://github.com/chrovis/cljam/blob/d68c01dd0c0e1b8a61829ada9c0c5e9aa18f4257/src/cljam/io/bcf/reader.clj#L230) took up most of the time, which does linear search per sample.
This PR removes the overhead of the linear search and improve the performance of the BCF reader by replacing the sequential collection returned from `read-typed-value` with a vector, not a lazy sequence.
Here are the profiling results before and after the change:
| before change | after change |
| :---: | :---: |
| <a href="https://github.com/chrovis/cljam/assets/27441/fc96ce6e-d332-4832-8bc0-3b3e7db126ac"><img width="500" alt="before change" src="https://github.com/chrovis/cljam/assets/27441/fc96ce6e-d332-4832-8bc0-3b3e7db126ac"></a> …
> Remove nth's linear search overhead in BCF reader

- src/cljam/io/cram/decode/record.clj
- src/cljam/io/cram/reader.clj
- src/cljam/io/cram/seq_resolver.clj
- src/cljam/io/cram/seq_resolver/protocol.clj
- test/cljam/io/cram/decode/record_test.clj
- test/cljam/io/cram/seq_resolver_test.clj
~~**Note:** This PR will be marked as ready for review after #306 has been merged.~~
This PR allows the CRAM reader to handle files with embedded references. With this update, we no longer need to specify any reference file to read CRAM files with embedded references.
According to the CRAM specification, if the encoder embeds a portion of the reference sequence into a slice, it allocates a dedicated block to store the raw (ASCII character) base sequence data for the reference sequence covering that slice. The content ID of this allocated block is pointed to by the "embedded reference bases block content ID" field in the slice header. If there is no embedded reference for the slice, this field's value will be `-1`. (See [§8.5](https://github.com/samtools/hts-specs/blob/401e2ec3e8ecf19fa89de …
> Support reading CRAM files with embedded references

- src/cljam/io/cram/core.clj
- src/cljam/io/cram/decode/record.clj
- src/cljam/io/cram/reader.clj
- test/cljam/io/cram/decode/record_test.clj
This PR enables the CRAM reader to automatically generate read names (QNAMEs) when they are absent in CRAM records.
According to section [§10.3](https://github.com/samtools/hts-specs/blob/401e2ec3e8ecf19fa89def74e9c27c1e40df341e/CRAMv3.tex#L1382) of the CRAM specification v3.1:
- If the `RN` field in the compression header's preservation map of a slice is set to `true`, the decoder will decode read names from the `RN` data series
- If the `RN` field is set to `false` and a record has a detached flag (`0x2`) set in the `CF` field, the decoder will also decode its read name from the `RN` data series
- For all other records, the decoder will automatically generate read names
- Although the CRAM specification does not define a specific method for generating read names, it suggests that names …
> Automatic read name generation for CRAM records

- src/cljam/io/cram/encode/record.clj
- src/cljam/io/cram/encode/tag_dict.clj
- src/cljam/io/cram/writer.clj
- test/cljam/io/cram/encode/record_test.clj
- test/cljam/io/cram/encode/tag_dict_test.clj
This PR refactors the CRAM writer to incorporate the tag dictionary construction into the preprocessing phase.
Previously, the CRAM writer had a separate pass to scan all records in the container for constructing the tag dictionary. This was done between the pass to encode CRAM records and the preprocessing pass (which is necessary for calculating various header components). This separate scanning pass made the CRAM writer's structure less clear and also caused inefficiency by requiring an additional scan.
By incorporating this scan into the preprocessing phase, the CRAM writer becomes easier to understand and eliminates the inefficiency of the extra scan.
To this end, the PR introduces a _tag dictionary builder_, which scans container records during preprocessing to construct the tag …
> CRAM tag dictionary construction at preprocessing phase

- src/cljam/io/cram/encode/context.clj
- src/cljam/io/cram/encode/record.clj
- src/cljam/io/cram/writer.clj
- test/cljam/io/cram/encode/record_test.clj
This PR refactors the CRAM writer implementation to simplify how values are passed between the CRAM writer and the record encoder.
Currently, the implementation involves a complex passing of various values and objects between the CRAM writer and the record encoder, including:
- Immutable data: CRAM header, preservation map, tag dictionary, substitution matrix, and data series/tag encodings
- Stateful objects: tag dictionary builder, data series/tag encoders
The current approach results in a CRAM writer cluttered with implementation details that are not within its concern, making the code difficult to maintain.
In this PR, all the above values and objects passed between the CRAM writer and the record encoder are organized into a context map. The context map has the following two types:
- …
> Refactor CRAM writer to organize encoding values into context maps

- src/cljam/io/cram/decode/structure.clj
- src/cljam/io/cram/encode/compressor.clj
- test/cljam/io/cram/data_series_test.clj
Currently, CRAM files generated by the CRAM writer containing LZMA-compressed blocks cannot be read correctly by samtools, resulting in an error.
```clojure
(require '[cljam.io.cram :as cram])
(with-open [r (cram/reader "test-resources/cram/medium.cram"
{:reference "hg19.fa"})
w (cram/writer "medium_lzma.cram"
{:reference "hg19.fa"
:tag-compressor-overrides (constantly :lzma)})]
(cram/write-header w (cram/read-header r))
(cram/write-alignments w (cram/read-alignments r) (cram/read-header r)))
```
```console
$ samtools view -T hg19.fa medium_lzma.cram
[E::lzma_mem_inflate] LZMA decode failure (error 7)
[E::cram_next_slice] Failure to decode slice
samtools view: error reading file "medium_lzma.cram"
$
```
According to the CRAM specification, the LZMA compression method used in CRAM is …
> Use XZ for LZMA compression in CRAM

- src/cljam/io/cram.clj
- src/cljam/io/cram/encode/partitioning.clj
- src/cljam/io/cram/encode/record.clj
- src/cljam/io/cram/writer.clj
- test/cljam/io/cram/encode/partitioning_test.clj
- test/cljam/io/cram/encode/record_test.clj
This PR introduces changes to fine-tune how containers and slices are partitioned when writing CRAM files.
The CRAM specification has flexibility in how containers and slices are partitioned, and it’s up to each CRAM encoder to decide how to do it. In CRAM index files, index entries are created for each slice, so how containers and slices are partitioned affects the performance of index access in CRAM files.
In particular, having _multiple-reference_ (or _multi-ref_) slices can make index access less efficient. So, CRAM encoders should aim to avoid creating multi-ref slices whenever possible, and even when they are necessary, the size of such slices should be kept to a minimum.
The change introduced in this PR is a bit complex, and this complexity mainly comes from these considerations. …
> Fine-grained partition of CRAM containers and slices

- src/cljam/io/cram.clj
- src/cljam/io/cram/data_series.clj
- src/cljam/io/cram/encode/context.clj
- src/cljam/io/cram/encode/partitioning.clj
- src/cljam/io/cram/encode/structure.clj
- src/cljam/io/cram/writer.clj
- test/cljam/io/cram/encode/record_test.clj
- test/cljam/io/cram_test.clj
This PR adds support for reference embedding during CRAM file writing.
The CRAM specification for reference embedding is as outlined in the PR for [reference embedding support in the CRAM reader](https://github.com/chrovis/cljam/pull/307#issue-2258310138).
This PR adds a new option `:embed-reference?` to enable reference embedding when writing CRAM files. By default, reference embedding is disabled. To enable it:
```clojure
(require '[cljam.io.cram :as cram])
(with-open [w (cram/writer "path/to/cram/file" { ..., :embed-reference? true, ... })]
... )
```
Reference embedding is only applicable when writing a CRAM file with the `SO:coordinate` declaration in the CRAM header. If the CRAM header lacks this declaration, an error will be raised. Like [CRAM index …
> Support reference embedding for CRAM writer

- src/cljam/io/cram/encode/mate_records.clj
- src/cljam/io/cram/encode/record.clj
- test/cljam/io/cram/encode/mate_records_test.clj
- test/cljam/io/cram/encode/record_test.clj
This PR adds support for encoding non-detached mate records. Once this has been merged, non-detached mate record encoding will always be enabled.
According to the CRAM specification, when mate records are in the same slice, the position of the downstream mate record relative to the upstream record can be indicated using the `NF` data series. In such cases, information related to mate records (such as `RNEXT`, `PNEXT`, and `TLEN`) can be obtained from the `RNAME` and `POS` of the mate record indicated by `NF`, reducing the need to retain these fields in separate data series. This approach is efficient in terms of CRAM file size.
When the mate record is outside the same slice or when fields like `RNEXT` and `PNEXT` are inconsistent between mates, the relevant information is stored in …
> Support for encoding non-detached mate records

- .github/workflows/coverage.yml
- .github/workflows/format.yml
- .github/workflows/main.yml
As mentioned in https://github.com/chrovis/cljam/pull/330#issuecomment-2572767463, Leiningen has been removed from the latest `ubuntu-latest` GitHub Action runner image. Some workflows in cljam rely on the `lein` installed in the `ubuntu-latest` image, which causes them to fail on the CI.
This PR updates those workflows by explicitly installing Leiningen with `DeLaGuardo/setup-clojure`. It also adds `actions/setup-java` to the `coverage` workflow to avoid depending on the `java` installed in the GA runner image, as in the other workflows.
> Explicitly install lein with setup-clojure for CI

- src/cljam/io/cram/codecs/rans4x8.clj
- src/cljam/io/cram/data_series.clj
- src/cljam/io/cram/encode/compressor.clj
- src/cljam/io/cram/encode/structure.clj
- test/cljam/io/cram/codecs/rans4x8_test.clj
This PR implements the rANS (rans4x8) encoder to allow the CRAM writer to use it for block compression.
With this PR, the default compressor for the following data series will be updated to rans4x8:
| Data Series | Default Compressor |
| :---: | :---: |
| `BF` | rans4x8 (Order 1) |
| `CF` | rans4x8 (Order 1) |
| `RI` | rans4x8 (Order 0) |
| `RL` | rans4x8 (Order 1) |
| `AP` | rans4x8 (Order 0) |
| `RG` | rans4x8 (Order 1) |
| `NS` | rans4x8 (Order 1) |
| `TS` | rans4x8 (Order 1) |
| `BA` | rans4x8 (Order 1) |
| `QS` | rans4x8 (Order 1) |
You can override the compressor for specific data series or tags by specifying `:r4x8-o0` (Order 0) or `:r4x8-o1` (Order 1) in the `:ds-compressor-overrides` / `:tag-compressor-overrides` options. 
For example, to set the compressor of the `FN` data …
> rANS (rans4x8) encoding support for CRAM block compression

- project.clj
- src/cljam/io/bam/reader.clj
- src/cljam/io/bam_index.clj
- src/cljam/io/protocols.clj
- src/cljam/io/sam.clj
- src/cljam/io/util/bin.clj
- test/cljam/io/bam/reader_test.clj
- test/cljam/io/sam_test.clj
- test/cljam/io/util/bin_test.clj
This PR adds a function `cljam.io.sam/read-mate-alignments` for BAM file which reads R1/R2 counterpart alignments of given alignments.
This function can be used for collecting alignments around some regions keeping pairs like `samtools view --fetch-pairs`.
```clj
(let [xs (sam/read-alignments reader {:chr "chr1", :start 1, :end 100000})]
(concat xs (sam/read-mate-alignments reader xs))
```
In the example above, it is necessary to recheck which alignment pairs with which. To make things easier, I added another function `cljam.io.sam/make-pairs` that returns a sequence with paired alignments grouped together.
```clj
(let [xs (sam/read-alignments reader {:chr "chr1", :start 1, :end 100000})]
(sam/make-pairs reader xs))
```
To achieve these functionalities, I implemented a function …
> Add a function to read mate alignments

- test/cljam/io/gff_test.clj
This PR fixes coding styles of test codes and does not introduce any changes of its behavior.
`clj-kondo` reports `test/cljam/io/gff_test.clj:319:70: error: Unresolved symbol: ?str` on the master branch.
I've removed the type hints in 909e6d2cc46fd00dfdd6d917b4a12efd6f9ecaad because adding type hints to the symbols  in `expr` of `clojure.test/are` has no effects on suppressing reflections.
In f13581a936505c98ba2028711e3d871e610057dc, I've also fixed some coding styles warned by `kibit`.
<details>
The strange behavior of the `:unresolved-symbol` error is due to differences in how metadata is handled.
[`clojure.test/are` uses `clojure.template/do-template`](https://github.com/clojure/clojure/blob/fb22fd778a272b034684a4ee94509552b46ee8a9/src/clj/clojure/test.clj#L594) which [replaces symbols …
> Fix some linter errors

- project.clj
- src/cljam/io/cram/data_series.clj
- src/cljam/io/cram/encode/structure.clj
- src/cljam/io/util/lsb/io_stream.clj
- test/cljam/io/cram/data_series_test.clj
- test/cljam/io/cram/encode/structure_test.clj
- test/cljam/io/util/byte_buffer_test.clj
- test/cljam/io/util/lsb/io_stream_test.clj
fixes: #332 
This PR fixes issues found in https://github.com/chrovis/cljam/pull/330#pullrequestreview-2522682459
Some functions under `cljam.io.cram` and `cljam.io.util.lsb` used the **checked** narrowing conversions of numerical values (`byte`, `int`, ...) or implicit conversions with typed method callings of Java core library.
These narrowing of numeric types works fine as long as `*unchecked-math*` is set to `true` or only non-negative integers are involved. However, if `*unchecked-math*` is `false` (which is the default) and a negative integer is provided, an exception is thrown.
In this PR, I have explicitly applied unchecked narrowing (`unchecked-byte`, `unchecked-int`, ...) to bypass range checks and ensure the intended output.
I have also fixed the `:gloval-vars` option in the …
> Fix overflow issues occurs when *unchecked-math* is disabled
